"""
Export Tools Module — Obsidian/Markdown Export, RSS Feed Generator,
Scheduled Search Configs, Video Comparison Data
"""

import json
import logging
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any, Optional
from xml.etree.ElementTree import Element, SubElement, tostring

import pandas as pd

logger = logging.getLogger(__name__)

BASE_DIR = Path(__file__).parent.parent
DATA_DIR = BASE_DIR / "data"
SCHEDULES_FILE = DATA_DIR / "scheduled_searches.json"


# ═══════════════════════════════════════════════════════════════════════
#  OBSIDIAN / MARKDOWN EXPORT
# ═══════════════════════════════════════════════════════════════════════
def export_to_obsidian(df: pd.DataFrame, title: str = "Obscurity Report") -> str:
    """
    Export results as Obsidian-compatible markdown with backlinks,
    tags, and metadata frontmatter.
    """
    now = datetime.now().isoformat()
    lines = [
        "---",
        f"title: {title}",
        f"date: {now}",
        f"videos: {len(df)}",
        "tags: [obscurity-engine, youtube, research]",
        "---",
        "",
        f"# {title}",
        f"Generated: {now}  ",
        f"Total videos: {len(df)}  ",
        "",
        "## Summary",
        f"- Zero-view videos: {len(df[df['views']==0]) if 'views' in df.columns else 0}",
        f"- Avg weirdness: {df['weirdness_score'].mean():.1f}" if 'weirdness_score' in df.columns else "",
        f"- Default filenames: {df['is_default_filename'].sum() if 'is_default_filename' in df.columns else 0}",
        "",
        "## Videos",
        "",
    ]

    for i, (_, row) in enumerate(df.iterrows()):
        vid_id = row.get("video_id", "")
        title_v = str(row.get("title", "Untitled"))
        channel = str(row.get("channel", "Unknown"))
        views = int(row.get("views", 0))
        weird = float(row.get("weirdness_score", 0))
        url = str(row.get("url", ""))
        tags_list = row.get("tags", [])
        desc = str(row.get("description", ""))[:200]

        # Obsidian-style entry with backlinks
        lines.append(f"### {i+1}. {title_v}")
        lines.append(f"- **Channel**: [[{channel}]]")
        lines.append(f"- **Views**: {views:,}")
        lines.append(f"- **Weirdness**: {weird:.0f}")
        lines.append(f"- **URL**: [{url}]({url})")
        lines.append(f"- **Duration**: {row.get('duration_fmt', 'N/A')}")
        lines.append(f"- **Age**: {int(row.get('age_days', 0)):,} days")

        if tags_list and isinstance(tags_list, list):
            tag_str = " ".join([f"#{t.replace(' ', '_')}" for t in tags_list[:10]])
            lines.append(f"- **Tags**: {tag_str}")

        if desc:
            lines.append(f"- **Description**: {desc}...")

        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Obscurity Engine v5 on {now}*")

    return "\n".join(lines)


def export_to_notion_csv(df: pd.DataFrame) -> str:
    """Export as CSV formatted for Notion database import."""
    cols = {
        "Title": df.get("title", pd.Series()),
        "Channel": df.get("channel", pd.Series()),
        "Views": df.get("views", pd.Series()),
        "Weirdness": df.get("weirdness_score", pd.Series()),
        "Duration": df.get("duration_fmt", pd.Series()),
        "Age (days)": df.get("age_days", pd.Series()),
        "URL": df.get("url", pd.Series()),
        "Default Filename": df.get("is_default_filename", pd.Series()),
    }
    export_df = pd.DataFrame({k: v for k, v in cols.items() if not v.empty})
    return export_df.to_csv(index=False)


# ═══════════════════════════════════════════════════════════════════════
#  RSS FEED GENERATOR
# ═══════════════════════════════════════════════════════════════════════
def generate_rss_feed(items: List[Dict], title: str = "Obscurity Engine Finds",
                      description: str = "Weirdest YouTube finds") -> str:
    """Generate an RSS 2.0 feed from a list of video entries."""
    rss = Element("rss", version="2.0")
    channel = SubElement(rss, "channel")

    SubElement(channel, "title").text = title
    SubElement(channel, "description").text = description
    SubElement(channel, "link").text = "https://youtube.com"
    SubElement(channel, "lastBuildDate").text = datetime.now().strftime("%a, %d %b %Y %H:%M:%S +0000")
    SubElement(channel, "generator").text = "Obscurity Engine v5"

    for entry in items:
        item = SubElement(channel, "item")
        SubElement(item, "title").text = str(entry.get("title", "Untitled"))
        SubElement(item, "link").text = str(entry.get("url", ""))
        SubElement(item, "description").text = (
            f"Views: {entry.get('views', 0)} | "
            f"Weirdness: {entry.get('weirdness_score', 0):.0f} | "
            f"Channel: {entry.get('channel', 'Unknown')}"
        )
        SubElement(item, "guid").text = str(entry.get("video_id", entry.get("url", "")))

        found_at = entry.get("found_at", entry.get("added_at", ""))
        if found_at:
            try:
                dt = datetime.fromisoformat(found_at)
                SubElement(item, "pubDate").text = dt.strftime("%a, %d %b %Y %H:%M:%S +0000")
            except (ValueError, TypeError):
                pass

    xml_str = tostring(rss, encoding="unicode", xml_declaration=False)
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + xml_str


# ═══════════════════════════════════════════════════════════════════════
#  SCHEDULED SEARCHES
# ═══════════════════════════════════════════════════════════════════════
def save_scheduled_search(name: str, config: Dict):
    """Save a search configuration for later re-use."""
    from modules.persistence import _load_json, _save_json, ensure_data_dir
    ensure_data_dir()
    schedules = _load_json(SCHEDULES_FILE, [])
    schedules.append({
        "name": name,
        "config": config,
        "created_at": datetime.now().isoformat(),
        "last_run": None,
        "run_count": 0,
    })
    _save_json(SCHEDULES_FILE, schedules)


def load_scheduled_searches() -> List[Dict]:
    from modules.persistence import _load_json
    return _load_json(SCHEDULES_FILE, [])


def update_schedule_run(name: str):
    from modules.persistence import _load_json, _save_json
    schedules = _load_json(SCHEDULES_FILE, [])
    for s in schedules:
        if s["name"] == name:
            s["last_run"] = datetime.now().isoformat()
            s["run_count"] = s.get("run_count", 0) + 1
    _save_json(SCHEDULES_FILE, schedules)


def delete_scheduled_search(name: str):
    from modules.persistence import _load_json, _save_json
    schedules = _load_json(SCHEDULES_FILE, [])
    schedules = [s for s in schedules if s["name"] != name]
    _save_json(SCHEDULES_FILE, schedules)


# ═══════════════════════════════════════════════════════════════════════
#  CHANNEL SCORE — Rate how obscure a channel is
# ═══════════════════════════════════════════════════════════════════════
def compute_channel_obscurity_score(df: pd.DataFrame) -> Dict[str, Any]:
    """
    Compute an overall obscurity score for a channel based on its videos.
    Returns a dict with score breakdown.
    """
    if df.empty:
        return {"total_score": 0, "breakdown": {}}

    n = len(df)
    score = 0
    breakdown = {}

    # View-based scoring
    avg_views = df["views"].mean() if "views" in df.columns else 0
    zero_pct = (len(df[df["views"] == 0]) / n * 100) if "views" in df.columns else 0
    if avg_views < 10:
        score += 30; breakdown["ultra_low_avg_views"] = 30
    elif avg_views < 50:
        score += 20; breakdown["very_low_avg_views"] = 20
    elif avg_views < 200:
        score += 10; breakdown["low_avg_views"] = 10

    if zero_pct > 50:
        score += 20; breakdown["majority_zero_views"] = 20
    elif zero_pct > 20:
        score += 10; breakdown["many_zero_views"] = 10

    # Default filename ratio
    default_pct = (df["is_default_filename"].sum() / n * 100) if "is_default_filename" in df.columns else 0
    if default_pct > 50:
        score += 15; breakdown["mostly_default_filenames"] = 15
    elif default_pct > 20:
        score += 8; breakdown["many_default_filenames"] = 8

    # Engagement ghost ratio
    if "likes" in df.columns and "comments" in df.columns:
        ghost_pct = len(df[(df["likes"] == 0) & (df["comments"] == 0)]) / n * 100
        if ghost_pct > 70:
            score += 15; breakdown["mostly_ghosts"] = 15
        elif ghost_pct > 30:
            score += 8; breakdown["many_ghosts"] = 8

    # Average weirdness
    avg_weird = df["weirdness_score"].mean() if "weirdness_score" in df.columns else 0
    if avg_weird > 50:
        score += 15; breakdown["high_avg_weirdness"] = 15
    elif avg_weird > 30:
        score += 8; breakdown["moderate_weirdness"] = 8

    # No description ratio
    if "desc_length" in df.columns:
        no_desc_pct = len(df[df["desc_length"] < 10]) / n * 100
        if no_desc_pct > 50:
            score += 5; breakdown["no_descriptions"] = 5

    return {
        "total_score": min(score, 100),
        "breakdown": breakdown,
        "stats": {
            "avg_views": round(avg_views, 1),
            "zero_view_pct": round(zero_pct, 1),
            "default_filename_pct": round(default_pct, 1),
            "avg_weirdness": round(avg_weird, 1),
            "total_videos": n,
        }
    }


# ═══════════════════════════════════════════════════════════════════════
#  HTML REPORT GENERATOR (enhanced)
# ═══════════════════════════════════════════════════════════════════════
def generate_html_report(df: pd.DataFrame, title: str = "Obscurity Engine — Field Report") -> str:
    """Generate a standalone dark-themed HTML report with embeds."""
    rows = ""
    embeds = ""
    for i, (_, r) in enumerate(df.head(50).iterrows()):
        vid_id = r.get("video_id", "")
        t = str(r.get("title", "")).replace("<", "&lt;").replace(">", "&gt;")
        rows += f'<tr><td>{i+1}</td><td><a href="{r.get("url","")}">{t}</a></td><td>{r.get("views",0):,}</td><td>{r.get("weirdness_score",0):.0f}</td><td>{r.get("channel","")}</td><td>{r.get("duration_fmt","")}</td><td>{r.get("age_days",0):,}d</td></tr>\n'
        if i < 10 and vid_id:
            embeds += f'<div class="embed"><h3>#{i+1} {t}</h3><iframe src="https://www.youtube.com/embed/{vid_id}" allowfullscreen></iframe><p>Views: {r.get("views",0):,} | W{r.get("weirdness_score",0):.0f} | {r.get("channel","")}</p></div>\n'

    avg_w = f"{df['weirdness_score'].mean():.1f}" if "weirdness_score" in df.columns and not df.empty else "0"
    zero_v = len(df[df["views"]==0]) if "views" in df.columns and not df.empty else 0

    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{title}</title>
<style>
body{{background:#0a0a0a;color:#33ff33;font-family:'Courier New',monospace;padding:20px;max-width:1200px;margin:0 auto}}
h1{{color:#66ff66;text-shadow:0 0 20px rgba(51,255,51,0.3);letter-spacing:4px;border-bottom:1px solid #1a8c1a;padding-bottom:10px}}
h2{{color:#ffb000}}h3{{color:#33ffff}}
table{{border-collapse:collapse;width:100%;margin:20px 0}}
td,th{{border:1px solid #1a8c1a;padding:8px;text-align:left;font-size:14px}}
th{{background:#111;color:#33ff33}}tr:hover{{background:#0a1a0a}}
a{{color:#ffb000;text-decoration:none}}a:hover{{color:#33ff33}}
.embed{{margin:20px 0;padding:15px;border:1px solid #1a8c1a;background:#050505}}
.embed iframe{{width:100%;height:315px;border:none}}
.embed p{{color:#1a8c1a;margin-top:8px}}
.stats{{display:flex;gap:20px;margin:20px 0}}.stat{{border:1px solid #1a8c1a;padding:15px;flex:1;text-align:center}}
.stat-val{{font-size:2em;color:#66ff66}}.stat-label{{color:#1a8c1a;font-size:0.8em;text-transform:uppercase;letter-spacing:2px}}
</style></head><body>
<h1>⌬ {title}</h1>
<p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Videos: {len(df)}</p>
<div class="stats">
<div class="stat"><div class="stat-val">{len(df)}</div><div class="stat-label">Total</div></div>
<div class="stat"><div class="stat-val">{zero_v}</div><div class="stat-label">Zero Views</div></div>
<div class="stat"><div class="stat-val">{avg_w}</div><div class="stat-label">Avg Weirdness</div></div>
</div>
<h2>Video Embeds (Top 10)</h2>
{embeds}
<h2>Full Results</h2>
<table><tr><th>#</th><th>Title</th><th>Views</th><th>Weird</th><th>Channel</th><th>Duration</th><th>Age</th></tr>
{rows}</table>
<hr><p style="color:#1a8c1a">Generated by Obscurity Engine v5</p>
</body></html>"""
